### ISSUE TITLE
Add support for `numpy.core._multiarray_umath.scalar` CPython type

### ISSUE THREAD

**Issue by jerrychen1990** [jpmml/sklearn2pmml#136]
I got an error while saving PMMLPipeline with StandardScaler  to .pmml files.
![image](https://user-images.githubusercontent.com/6780752/53731562-278c8000-3eb6-11e9-910d-0b346d1e58c1.png)

here is my code:
![image](https://user-images.githubusercontent.com/6780752/53731655-720dfc80-3eb6-11e9-9fc1-e2ce5fd71d0e.png)

**Comment by vruusmann** [comment]
Currently, the problem is that you're working with "synthetic" datasets `x` and `y`, which have been generated using `numpy.rand` utility functions. Apparently, these Numpy functions "contaminate" the resulting array/series objects with CPython types.

Try to switch to "normal" datasets instead. For example, if you load `x` and `y` from a regular CSV file (eg. using the `pandas.read_csv` utility function), then there are no CPython types present, and everything should work as advertised.

**Comment by jerrychen1990** [comment]
@vruusmann 
I tried to load data from a .csv file, but it seems still not working:
![image](https://user-images.githubusercontent.com/6780752/53777538-b17b2e00-3f34-11e9-8c89-799a179f4980.png)
![image](https://user-images.githubusercontent.com/6780752/53777547-b9d36900-3f34-11e9-86f3-f091de8c30da.png)

**Comment by vruusmann** [comment]
> sklearn2pmml: 0.38.0

You are using an outdated SkLearn2PMML package version. Please upgrade to the latest 0.43.0, and your problem will be solved.

The support for `numpy.core._multiarray_umath.scalar` type was added here:
https://github.com/jpmml/jpmml-sklearn/commit/78c8104014687a80eabfe4edbdcd74fbeed4ef48
