### ISSUE TITLE
Keep the domain information available during conversion

### ISSUE THREAD

**Issue by tyers** [jpmml/sklearn2pmml#193]
Hi Villu,
I'm just testing out the updates you pushed to resolve #189 and I am now getting the following error:
```
java.lang.IllegalArgumentException: Field CREATION_DATETIME is frozen for type information updates
        at sklearn2pmml.decoration.Domain.updateDataField(Domain.java:57)
        at sklearn.Transformer.updateFeatures(Transformer.java:79)
        at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:114)
        at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
        at sklearn.Initializer.encodeFeatures(Initializer.java:41)
        at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:116)
        at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:83)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:203)
        at org.jpmml.sklearn.Main.run(Main.java:145)
        at org.jpmml.sklearn.Main.main(Main.java:94)
```
Checking out the code referenced in the trace it looks like this error was added a couple of days after that fix and, if i'm reading the java correctly, is effectively making it impossible to apply a Domain decorator to the same field twice within the same pipeline, even if the properties of that domain are the same.

While it seems logical that the definition of the field needs to be frozen once set, it is counter intuitive that it is not possible to apply another domain decorator to the field with the same properties as this is not actually changing the field definition.

Thinking a bit more broadly; if my understanding of the rest of the process is correct the collision detection throughout the conversion process is based entirely on the automatically generated field names within the PMML document; and these are almost always only considering the input field and the transformer class.
If this is the case i guess it is going to be a bit like a game of whack-a-mole with these kind of issues i'm encountering as i have loads of template feature derivations which reuse field-transformer pairs.
Very much thinking aloud here, but would it be possible to replicate what you have done for the duration transformer classes and embed the parameters for other supported transformations in the feature names throughout?

thanks again

**Comment by vruusmann** [comment]
> Checking out the code referenced in the trace it looks like this error was added a couple of days after that fix and

This is a feature, not an error.

The complete code change: https://github.com/jpmml/jpmml-sklearn/commit/6f05382d1c045e122d62a521bb39ce0c97ae2fcf

> effectively making it impossible to apply a Domain decorator to the same field twice within the same pipeline

Scikit-Learn/Python is a weakly/duck-typed language, whereas PMML is a strictly typed language. The PMML converter thus needs to collect type hints in order to figure out the maximally specific type for each column. However, it's advisable for you to assist it by static explicitly your assumptions about a particular column by applying a `sklearn2pmml.decoration.Domain` transformer to it (as the first step of a pipeline).

You can make this "type definition statement" only once.

> .. apply another domain decorator to the field with the same properties as this is not actually changing the field definition.

Applying identical `Domain` transformers doesn't add any value. Keep the first instance, and simply try to get rid of all the other instances. Reorder `DataFrameMapper` rows if necessary.

For example:
```python
mapper = DataFrameMapper([
  ("x1", ContinuousDomain()),
  (["x1", "x2"], MultiDomain([None, ContinuousDomain()])) # x1 is already defined, so use `None` as domain
])
```

> i have loads of template feature derivations which reuse field-transformer pairs.

You should probably refactor your "mapper library" to make it more systematic.

The current `DerivedField` element naming policy is optimal. It simply helps you detect duplicate "transformed feature definitions" early in the game. If you insist on having duplicates, then simply use the `Alias` decorator to rename them.

> would it be possible to replicate what you have done for the duration transformer classes

The duration transformer case was a legitimate bug, because the auto-generated field name did not consider the "year dimension". Now you can have `days_since_year(x1, 2018)` and `days_since_year(x1, 2019)`, whereas before they were collapsed to the same `days_since_year(x1)`.

**Comment by vruusmann** [comment]
Right now the class `org.jpmml.sklearn.SkLearnEncoder` simply remembers the names of fields (`DataField` elements) that have been decorated as `Set<FieldName>`.

However, it would be beneficial to store the actual domain definition as `Map<FieldName, sklearn2pmml.decoration.Domain>`. The domain information can be used for all sorts of value space validation purposes.

**Comment by vruusmann** [comment]
> Would it be possible to .. embed the parameters for other supported transformations in the feature names throughout?

I'm currently solving https://github.com/jpmml/jpmml-sklearn/issues/119 and ran across a nice example why the above (generating unique names for functionally equivalent derived fields) is not a good/clean solution.

Scikit-Learn happily fits the following:
```python
df = pandas.read_csv("Iris.csv", na_values = ["N/A", "NA"])

columns = df.columns.tolist()
df_X, df_y = (df[columns[: -1]], df[columns[-1]])

pipeline = PMMLPipeline([
	("pipeline", OneVsRestClassifier(Pipeline([
		("minmax", MinMaxScaler()),
		("logreg", LogisticRegression())
	])))
])
pipeline.fit(df_X, df_y)
```

However, the JPMML-SkLearn library rejects this "repeated scaling" with the following exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: Field mix_max_scaler(Sepal.Length) is already defined
        at org.jpmml.converter.PMMLEncoder.checkName(PMMLEncoder.java:279)
        at org.jpmml.converter.PMMLEncoder.addDerivedField(PMMLEncoder.java:148)
```

To solve the issue, simply extract the `MinMaxScaler()` step to the higher level, so that the same scaled value would be visible across all `OneVsRestClassifier()` branches:
```python
pipeline = PMMLPipeline([
	("minmax", MinMaxScaler()),
	("pipeline", OneVsRestClassifier(Pipeline([
		("logreg", LogisticRegression())
	])))
])
```
