### ISSUE TITLE
transformer  with "does not specify the number of input features" error hits

### ISSUE THREAD

**Issue by chiyibu** [jpmml/sklearn2pmml#201]
hi, i used transformers under sklearn2pmml.preprocessing package, and always get "java.lang.IllegalArgumentException: The transformer object of the first step (Python class sklearn2pmml.preprocessing.PowerFunctionTransformer) does not specify the number of input features
" error
Are those transformers not usable?

**Comment by vruusmann** [comment]
> java.lang.IllegalArgumentException: The transformer object of the first step does not specify the number of input features

The converter needs to know the "description" of the dataset (number of columns, their names and data types) that enters the pipeline. Sometimes it is possible to collect all this information from the wrapper `PMMLPipeline` object. If not, then the converter queries the first step of the pipeline (typically some transformer) for the same.

> Are those transformers not usable?

Right now the converter is querying the `sklearn2pmml.preprocessing.PowerFunctionTransformer` object, which doesn't collect this information, because it is not supposed to be the first step of a pipeline.

You can always resolve this issue by inserting a `sklearn_pandas.DataFrameMapper` or `sklearn.compose.ColumnTransformer` into the first position of your pipeline:

```python
pipeline = PMMLPipeline([
  ("domain", DataFrameMapper([
    (df.columns.values, ContinuousDomain())
  ])),
  ("transformer", PowerFunctionTransformer(power = 2)),
  ("estimator", ..),
])
```
