### ISSUE TITLE
Packing estimator and mapper together

### ISSUE THREAD

**Issue by KidCrippler** [jpmml/sklearn2pmml#22]
Is there a way to pack both .pkl files (estimator and mapper) in one file? That would really help me a lot as the current java model infrastructure we use in my company only supports a single file per model.
I could pack them both in a .zip file but that would be very gruesome.
I could also just provide the jpmml file instead of 2 .pkl files, but that would inflate the model file sizes and require a lot of extra bandwith.

10x

**Comment by vruusmann** [comment]
I've been thinking about this problem lately in the context of an online conversion service - it would be much more easier/intuitive to build an UI for a single file upload vs. two file uploads.

The answer to this question is to add support for `sklearn.pipeline.Pipeline` class (see https://github.com/jpmml/jpmml-sklearn/issues/3). Basically, you would be creating a two-step pipeline, where the first step is a `DataFrameMapper`, and the second step is an `Estimator` of your choice:
```Python
pipeline = Pipeline([
  ("mapper", iris_mapper),
  ("estimator", iris_classifier)
])

joblib.dump(pipeline, "iris_pipeline.pkl")
```

Also, Pipelines are needed anyway in order to support Scikit-Learn feature extraction and selection transformations (see https://github.com/jpmml/sklearn2pmml/issues/15; you could introduce any number of steps between the initial "mapper" step and the final "estimator" step).
