### ISSUE TITLE
Dataframe input for DateDomain

### ISSUE THREAD

**Issue by bindernet** [jpmml/sklearn2pmml#226]
Hi Villu,
I can't seem to input a pandas dataframe into the DateDomain decorator transform method.
The flat_transform method in util.py is attempting to call ravel() on it's input.

This a problem for me when using a DataFrameMapper with input_df=True
Here is a minimal example without the DataFrameMapper, but the same error. 

```
from sklearn2pmml.decoration import DateDomain
from sklearn2pmml import pandas as pd

X = pd.DataFrame({'date_col': [pd.to_datetime('2020-02-20')]})

print("Works:", DateDomain().fit_transform(X.values))
DateDomain().fit_transform(X)
```

Output:
```
Works: [[datetime.datetime(2020, 2, 20, 0, 0)]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/2020/pmml_pipes/date2.py", line 7, in <module>
    DateDomain().fit_transform(X.date_col)
  File "/home/xxx/.local/lib/python3.8/site-packages/sklearn/base.py", line 553, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/decoration/__init__.py", line 110, in transform
    X = cast(X, self.dtype)
  File "/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/util.py", line 7, in cast
    return flat_transform(X, func)
  File "/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/util.py", line 25, in flat_transform
    X = X.ravel()
  File "/home/xxx/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5179, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ravel'
```

**Comment by vruusmann** [comment]
Most decorator classes are supposed to be used from within pipelines, dataframe mappers, or column transformers. The surrounding meta-estimator then takes care of first unpacking a `DataFrame` to a Numpy array, and then packing it back. This process should work fine even if the number of columns is greater than one.

Something like this:
```python
mapper = DataFrameMapper([
  (["first_date", "second_date"], [DateDomain(), ..])
])
```

I believe most SkLearn2PMML  decorator and custom transformer classes are not prepared to handle `DataFrame` input. However, given that the issue is very well localized (a single `numpy.ravel` function call?), then it might be considered.

**Comment by bindernet** [comment]
For what it's worth:
My use case is that I have set `input_df=True` in the `DataFrameMapper` so have `DataFrame` input.
The reason I've done this is that I wanted to use `X['my_col']` inside an `ExpressionTransformer` elsewhere in the `DataFrameMapper`, but I guess I can live without it. (or create a pull request ;)

As far as I can tell (so far) continuous and categorical decorators do work with dataframe input. Might be nice to do for consistency.
