### ISSUE TITLE
pkl-to-pmml errror

### ISSUE THREAD

**Issue by andylhc** [jpmml/sklearn2pmml#257]
hi,^.^
the problem for me is :
code:  
[![DWhX6g.png](https://s3.ax1x.com/2020/12/01/DWhX6g.png)](https://imgchr.com/i/DWhX6g)
error:  
[![DWI8wd.png](https://s3.ax1x.com/2020/12/01/DWI8wd.png)](https://imgchr.com/i/DWI8wd)

(Our company turned off the virtual machine copy function, so I can only take screenshots,(°ー°〃) )

**Comment by andylhc** [comment]
[![DWIX6O.png](https://s3.ax1x.com/2020/12/01/DWIX6O.png)](https://imgchr.com/i/DWIX6O)
When I want to add woe conversion to pipeline and output pmml file, I find it difficult.
more cases?

**Comment by vruusmann** [comment]
If you want to use custom transformers/estimators in your Scikit-Learn pipeline, then you need to implement and register custom converters as explained here: https://github.com/jpmml/sklearn2pmml-plugin

I think it's possible to simplify your pipeline so that the WoE calculation can be implemented using the standard/already supported converters.

First, you don't need a custom estimator class for probability post-processing. See the `sklearn2pmml.pipeline.PMMLPipeline.predict_proba_transformer` attribute (and the associated `PMMLPipeline.predict_proba_transform` method).

Second, you don't need a custom transformation for WoE calculation. See the `sklearn2pmml.preprocessing.ExpressionTransformer` class.

Key idea:
```python
pipeline = PMMLPipeline([
  ("classifier", LGBMClassifier())
], predict_proba_transformer = ExpressionTransformer(..))
pipeline.fit(X_train, y_train)
pipeline.predict_proba_transform(X_test)
```
