### ISSUE TITLE
Changing the behaviour of Scikit-Learn trees (re-purposing `DecisionTreeClassifier` as a ruleset classifier)

### ISSUE THREAD

**Issue by Linging** [jpmml/sklearn2pmml#307]
Hi. I have strange problem caused by unnormal use of sklearn. For some reason, I need to transform a manual rule-based decision tree to pmml file. So I faked the tree model in sklearn.tree._Tree like that:
```python
from sklearn.tree._tree import Tree

class FakeTree(Tree):
    @property
    def children_left(self):
        return np.array([1, -1, -1], dtype=np.intp)
    @property
    def children_right(self):
        return np.array([2, -1, -1], dtype=np.intp)
    @property
    def feature(self):
        return np.array([2, -2, -2], dtype=np.intp)
    @property
    def impurity(self):
        return np.array([0.6666, 0., 0.5], dtype=np.float64)
    @property
    def n_classes(self): 
        return np.array([3], dtype=np.intp)
    @property
    def n_node_samples(self):
        return np.array([150, 50, 100], dtype=np.intp)
    @property    
    def threshold(self):
        return np.array([2.49999, -2, -2], dtype=np.float64) 
    @property    
    def value(self):   
        return np.array([[[50, 50, 50]], [[50, 0, 0]], [[0, 50, 50]]], dtype=np.float64)   
    @property 
    def weighted_n_node_samples(self): 
        return np.array([150, 50, 100], dtype=np.intp)
    @property
    def n_leaves(self):
        return np.int32(2)    

    def __init__(self, a, b, c):  
        self.capacity = 3     
        self.max_depth = 1   
        self.max_n_classes = 3    
        self.n_features = 4   
        self.n_outputs = 1   
        self.node_count = 3

from sklearn import tree
dt = tree.DecisionTreeClassifier()
dt.tree_ = FakeTree(dt.n_features_, dt.n_classes_, dt.n_outputs_)
```

I got an almost identical dt.tree_ object, this method seems to work. But when I generate pmml, an error occured

```
Standard output is empty
Standard error:
ʮһ 25, 2021 3:30:14  org.jpmml.sklearn.Main run
Ϣ: Parsing PKL..
ʮһ 25, 2021 3:30:14  org.jpmml.sklearn.Main run
Ϣ: Parsed PKL in 13 ms.
ʮһ 25, 2021 3:30:14  org.jpmml.sklearn.Main run
Ϣ: Converting PKL to PMML..
ʮһ 25, 2021 3:30:14  sklearn2pmml.pipeline.PMMLPipeline initTargetFields
: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
ʮһ 25, 2021 3:30:14  sklearn2pmml.pipeline.PMMLPipeline initActiveFields
: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.active_fields' is not set. Assuming [x1, x2, x3, x4] as the names of active fields
ʮһ 25, 2021 3:30:14  org.jpmml.sklearn.Main run
: Failed to convert PKL to PMML
java.lang.IllegalArgumentException
   at numpy.core.NDArrayUtil.asJavaList(NDArrayUtil.java:98)
   at numpy.core.NDArrayUtil.asJavaList(NDArrayUtil.java:79)
   at numpy.core.NDArrayUtil.getContent(NDArrayUtil.java:62)
   at numpy.core.NDArray.getArrayContent(NDArray.java:91)
   at org.jpmml.python.PythonObject.getArray(PythonObject.java:168)
   at org.jpmml.python.PythonObject.getNumberArray(PythonObject.java:209)
   at sklearn.tree.Tree.getValues(Tree.java:40)
   at sklearn.tree.TreeUtil.encodeTreeModel(TreeUtil.java:285)
   at sklearn.tree.TreeUtil.encodeTreeModel(TreeUtil.java:274)
   at sklearn.tree.TreeClassifier.encodeModel(TreeClassifier.java:50)
   at sklearn.tree.TreeClassifier.encodeModel(TreeClassifier.java:32)
   at sklearn.Estimator.encode(Estimator.java:103)
   at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:233)
   at org.jpmml.sklearn.Main.run(Main.java:217)
   at org.jpmml.sklearn.Main.main(Main.java:143)
```

Did I overlook any key points? or I'm wrong from the start. Thank you very much if you can give me a hint.

`sklearn2pmml = 0.76.1
numpy = 1.19.2
python = 3.7.0`

**Comment by vruusmann** [comment]
> Did I overlook any key points?

Your `FakeTree` class uses the `@property` annotation to override base `sklearn.tree.Tree` class attributes. This works in 100% Python environment, but it does not work in the SkLearn2PMML/JPMML-SkLearn stack environment (because dynamic Python properties cannot be serialized using Pickle format, they only exist in live environments?).

Also, the SkLearn2PMML/JPMML-SkLearn stack is not aware of your custom `FakeTree` class definition. I'm actually surprised that you're getting an `IllegalArgumentException` at that late stage, and not much-much sooner.

**Comment by vruusmann** [comment]
Here's some things you could try:

1. Instead of using a custom `FakeTree` class, cannot you set `sklearn.tree.Tree` attributes directly? The idea is to make sure that all tree attributes are "statically defined", and persistanbe in Pickle data format.

2. If this use case a one-off, or will you be using this functionality in the future as well? If it's the latter, then perhaps we should define a special-purpose `RuleSetClassifier` cutom estimator type (into the SkLearn2PMML package) instead of hacking the `sklearn.tree.DecisionTreeClassifier` class.

**Comment by vruusmann** [comment]
> I can’t modify the attributes of sklearn.tree.Tree because _tree.pxd did not provide a suitable interface, so I use @Property to avoid the error objects is not writeable.

OK, the `@property` approach looks to be a dead-end then. The attribute override using `@property` annotations works in 100% Python environment, but it does not work in Python+Java hybrid environment, because the Java side (as implemented using [Pickle](https://github.com/irmen/pickle) and [JPMML-Python](https://github.com/jpmml/jpmml-python) libraries) cannot "see" and therefore follow these annotations.

> Maybe I should use components provided by JPMML such as org.pmml.tree.Node to complete the script of the rule model, and manually generate a PMML object.

The `org.dmg.pmml.tree.Node` belongs to the decision tree model type (package `org.dmg.pmml.tree`). If you are looking to implement ruleset models, then you should consider using the ruleset model type instead (package `org.dmg.pmml.ruleset`).

The decision tree model type is about defining a "**hierarchy** of rules"; the evaluation is about going deeper into the hierarchy, until a terminal rule is reached.

In contrast, the ruleset model type is about defining a "**linear sequence** of rules"; the evaluation is about testing rules one-by-one, and returning the first match.

See what concept reflects your custom model better.

In terms of Java API for PMML, then there are many abstraction layers available (when working with Python objects):
1. [JPMML-SkLearn](https://github.com/jpmml/jpmml-sklearn) - Scikit-Learn based models.
2. [JPMML-Python](https://github.com/jpmml/jpmml-python) - Generic Python based models.
3. [JPMML-Converter](https://github.com/jpmml/jpmml-converter) - Boilerplate conversion functionality. Will automate large parts of PMML markup generation, you can focus only on defining fields and model data structures.
4. [JPMML-Model](https://github.com/jpmml/jpmml-model) - Low-level PMML reading and writing functionality.

> As for RuleSetClassifier, some users of ours, wanna to build a decision tree step-by-step.

Do you know any **_existing_** Python packages that are designed/used for this purpose? I would rather add support for an existing package/model data structure, than start inventing my own.

I've previously checked out the [Skope-rules](https://github.com/scikit-learn-contrib/skope-rules) package, any comments on that?

**Comment by vruusmann** [comment]
The [JPMML-Python](https://github.com/jpmml/jpmml-python) library (which underlies the JPMML-SkLearn library) supports parsing/converting [Treelib](https://github.com/caesar0301/treelib) package models.

Treelib is 100% written in Python. And Treelib's tree and node data structures are much more flexible than their Scikit-Learn equivalents.

Therefore, when developing custom tree-based models, consider basing your work on the `treelib` package.
