### ISSUE TITLE
Is Isotonic regression model supported? 

### ISSUE THREAD

**Issue by EagleDangar** [jpmml/sklearn2pmml#322]
I tried to convert the Isotonic pipeline to PMML , it converted but not able to get the right prediction in c++. 

using cPMML library in c++. 

python code 
```python
from sklearn.isotonic import IsotonicRegression
from sklearn.linear_model import LinearRegression
from sklearn2pmml import sklearn2pmml
from sklearn2pmml.pipeline import PMMLPipeline

import pandas as pd

def export_as_pmml():
    
    data = pd.read_csv("data_for_new_isotonic_model.csv")
    name = "calib_isotonic_model.xml"
    ## Train the model with PMML wraper
    regressor_pipeline = PMMLPipeline(
        [
            (
                "regression",
                IsotonicRegression(out_of_bounds="clip")
            )
        ]
    )
    regressor_pipeline.fit(data['prob_pred'], data['prob_true'])
    print(regressor_pipeline.score(data['prob_pred'], data['prob_true']))
    
    sklearn2pmml(regressor_pipeline, name ,with_repr=True)
    print(f"Successfully exported as {name}!!")
```

c++ code 

```c
#include <iostream>
#include <unordered_map>

#include "cPMML.h"

template<typename K, typename V>
void print_map(std::unordered_map<K, V> const &m)
{
    for (auto const &pair: m) {
        std::cout << "{" << pair.first << ": " << pair.second << "}\n";
    }
}

// using namespace std;
int main() {

	std::string model_filepath = "calib_isotonic_model.xml";
	cpmml::Model model(model_filepath);
	std::unordered_map<std::string, std::string> sample = {
		{"prob_pred","16000000"}
	};
	print_map(sample);
	std::cout << "score: " << model.predict(sample) << std::endl;

  	return 0;
}
```

`

help me here Thanks !!!

**Comment by vruusmann** [comment]
> Is Isotonic regression model supported? 

Yes it is.

It should be obvious from your own example, where the `sklearn2pmml.sklearn2pmml` utility function completes successfully, and gives you a PMML document that you can feed to another application.

> using cPMML library in c++.

Are you sure that the cPMML library is able to deal with isotonic regressions correctly?

> help me here Thanks !!!

I can't help you, because I don't have access to your data file(s).

You help yourself - for starters, make predictions using the [JPMML-Evaluator-Python](https://github.com/jpmml/jpmml-evaluator-python) library, and see if its predictions come back as correct or not.

**Comment by vruusmann** [comment]
See https://github.com/AmadeusITGroup/cPMML/issues/10

**Comment by EagleDangar** [comment]
Thanks ! I verified it in the Java emulator. It is working fine. But not with cPMML not sure.
