### ISSUE TITLE
Is pipeline.fit(X, y) required?

### ISSUE THREAD

**Issue by Rajeshyd0308** [jpmml/sklearn2pmml#346]
Hello, I am new to using sklearn2pmml can some one help me with these issues?

```python
import pickle
from sklearn2pmml import PMMLPipeline, sklearn2pmml
with open("clf_best.pkl", 'rb') as pkl:
  clf_best = pickle.load(pkl)
pipeline = PMMLPipeline([
   ('clf', clf_best)
])
```

Here my clf_best has already been trained on the dataset. Do I need to do pipeline.fit(X, y) on my dataset?

**Comment by vruusmann** [comment]
The `fit(X, y)` method must be called at least once during the lifetime of a Scikit-Learn estimator class (this includes the `Pipeline` meta-estimator class), because this is how the "learned state" gets initialized.

If your `clf_best` object has already been fitted, then it **does not need to be re-fitted** after "embedding" it into `sklearn2pmml.pipeline.PMMLPipeline`. Actually - re-fitting would overwrite (destroy) its existing learned state.

However, if the `clf_best` object is unfitted so far, then you should invoke `PMMLPipeline.fit(X, y)` at the end of your sample script.
