### ISSUE TITLE
StandardScaler in pipeline causes PMML export to error out

### ISSUE THREAD

**Issue by nsriram13** [jpmml/sklearn2pmml#35]
I am getting an error when I try and export the `StandardScaler` transformer through a `PMMLPipeline`.  Here is the stack trace:

```
SEVERE: Failed to convert
java.lang.ClassCastException: sklearn.preprocessing.StandardScaler cannot be cast to sklearn.HasNumberOfFeatures
	at sklearn2pmml.PMMLPipeline.initFeatures(PMMLPipeline.java:153)
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:115)
	at org.jpmml.sklearn.Main.run(Main.java:144)
	at org.jpmml.sklearn.Main.main(Main.java:93)
Exception in thread "main" java.lang.ClassCastException: sklearn.preprocessing.StandardScaler cannot be cast to sklearn.HasNumberOfFeatures
	at sklearn2pmml.PMMLPipeline.initFeatures(PMMLPipeline.java:153)
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:115)
	at org.jpmml.sklearn.Main.run(Main.java:144)
	at org.jpmml.sklearn.Main.main(Main.java:93)
```

Below is the code that reproduces this error.

```python
import numpy as np
from sklearn import datasets, svm
from sklearn.preprocessing import StandardScaler
from sklearn2pmml import sklearn2pmml
from sklearn2pmml import PMMLPipeline

iris = datasets.load_iris()
X = iris.data
y = iris.target

X = X[y != 0, :2]
y = y[y != 0]
y = y.astype(np.float)

feat_normalizer = StandardScaler()
clf = svm.SVC(kernel='rbf', gamma=10)

clf_module = PMMLPipeline([('normalizer', feat_normalizer), ('classifier', clf)])
clf_module.fit(X, y)
sklearn2pmml(clf_module, "classifier.pmml", with_repr=True)
```

Any thoughts on what might be going on here?

**Comment by vruusmann** [comment]
The converter needs to know that how many features are "entering" the pipeline. If all else fails (see below), then the converter makes attempts to ask this information from the first step of the pipeline. However, class `StandardScaler` does not specify the `num_features` (or similar) attribute.

Your script can be "fixed" in many ways, but the simplest would be to convert `X` and `y` arguments from Numpy arrays to `pandas.DataFrame` and `pandas.Series` objects:
```
from pandas import DataFrame, Series

X = DataFrame(X, columns = iris.feature_names[:2])
y = Series(y, name = "Species")
```

The added benefit of specifying feature and target names is that this information will be incorporated into "model schema" (otherwise, features would be called `x1`, `x2`, .., `x{n}`, and the target would be called `y`, which is not helpful in long term).

Alternatively, you may keep `X` and `y` arguments as Numpy arrays, and specity their column names as `PMMLPipeline.active_fields` and `PMMLPipeline.target_field` attributes:
```
clf_module.active_fields = np.array(iris.feature_names[:2])
clf_module.target_field = "Species"
```

**Comment by vruusmann** [comment]
@nsriram13 If you upgrade to SkLearn2PMML version 0.20.2(+), then you will be able to convert your pipeline as-is.

**Comment by nsriram13** [comment]
@vruusmann 👍  Many thanks! I can confirm the fix works!
