### ISSUE TITLE
Is there a way to combine multiple models into a single pmml file?

### ISSUE THREAD

**Issue by liuhuanshuo** [jpmml/sklearn2pmml#358]
I can convert my machine learning model from pkl to a pmml file using sklearn2pmml for java use, which is great.

But now I have a problem. I have multiple lgb models such as lgb1, lgb2... Lgb5.

I want to predict a probability from each of these five models, and then calculate their average as the final result.

But the only way I can do this is with code like,
```python
pipeline_test = PMMLPipeline(
steps=[("mapper", mapper),
("classifier", clf_1)])
```
In this way, 5 pmml are produced respectively, and then the five pmml are calculated five times, and finally a score is calculated

I would like to know if sklearn2pmml can implement the above tasks in a pipeline, so that only one pmml file is needed in the end

**Comment by vruusmann** [comment]
Cross-linking with https://github.com/jpmml/jpmml-sklearn/issues/52

> I have multiple lgb models such as lgb1, lgb2... Lgb5.
> I want to predict a probability from each of these five models, and then calculate their average as the final result.

Let's assume that the current technical capabilities of the SkLearn2PMML/JPMML-SkLearn stack are not a problem. Then, how would you implement a proper solution in Python currently? Is there some third-party Python package available that is suitable for such work?

Important: the proposed solution must work within Scikit-Learn's pipeline framework (otherwise it wouldn't be pickleable, and therefore reusable across Python sessions/environments). So, using lambdas is not allowed!

**Comment by vruusmann** [comment]
How about `sklearn.ensemble.VotingRegressor`?
https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.VotingRegressor.html

Can you implement your solution using it? Please note that you do not need to invoke `VotingRegressor.fit(X, y)` method, because the child models are already fitted.

**Comment by liuhuanshuo** [comment]
> How about `sklearn.ensemble.VotingRegressor`? https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.VotingRegressor.html

Thank you, I will study the contents of this link.

If feasible, I will add a reply here
