### ISSUE TITLE
ExpressionTransformer : Name 'X' refers to a row vector.

### ISSUE THREAD

**Issue by liuhuanshuo** [jpmml/sklearn2pmml#367]
I used ExpressionTransformer for feature conversion

This feature is a float, converting to 100 if it is greater than 1 and 0 if it is less than 1

So I can write the code like this
```
ExpressionTransformer("100 if X > 1 else 0")
```
That way it works, and the transformation succeeds, using fit_transform is correct

But an error occurred while saving the pmml.
```
Exception in thread "main" java.lang.IllegalArgumentException: Name 'X' refers to a row vector. Use an array indexing expression X[<column index>] or X[<column name>] to refer to a specific row vector element
```
I'm sure there are other functions that can do this conversion, but what if I must use ExpressionTransformer

Why can I convert but not save?

**Comment by vruusmann** [comment]
The `ExpressionTransformer` transformation is applied to a rows of a data matrix (eg. `pandas.DataFrame`, `numpy.ndarray`). Therefore, the `X` argument is a row vector, not a scalar.

Your expression `100 if X > 1 else 0` therefore reads: "if row is greater than 1, do this, else do that". This does not make sense, because "row" cannot be compared with scalar reference values. You must convert the row to a scalar first.

> Exception in thread "main" java.lang.IllegalArgumentException: Name 'X' refers to a row vector. Use an array indexing expression X[<column index>] or X[<column name>] to refer to a specific row vector element

Did you pay any attention to this error message? It literally tells you to use the array indexing syntax `X[col]` to select a value from your row vector.

```python
ExpressionTransformer("100 if X[0] > 1 else 0")
```

> That way it works, and the transformation succeeds

Your transformation does not make any sense - comparing a row vs. scalar. It may evaluate, but the return value of this evaluation is non-sensical.

**Comment by liuhuanshuo** [comment]
> ExpressionTransformer("100 if X[0] > 1 else 0")
Of course I noticed the hint, and I tried it the first time
```
TypeError: 'float' object is not subscriptable
```

**Comment by liuhuanshuo** [comment]
> > ExpressionTransformer("100 if X[0] > 1 else 0")
Of course I noticed the hint, and I tried it the first time

```
TypeError: 'float' object is not subscriptable
```

**Comment by liuhuanshuo** [comment]
> ExpressionTransformer("100 if X[0] > 1 else 0")

Of course I noticed the hint, and I tried it the first time
 ```
TypeError: 'float' object is not subscriptable
```

**Comment by liuhuanshuo** [comment]
I don't know if you've ever tried something like this.

If the target is a float, no error is reported using the following code，The transformation can be successfully performed using fit_transform
```
ExpressionTransformer("100 if X > 1 else 0")
```
It just can't be saved
```
Name 'X' refers to a row vector
```

But with the following code, an error will be reported directly!
```
ExpressionTransformer("100 if X[0] > 1 else 0")
```

**Comment by vruusmann** [comment]
The `EstimatorTransformer` transformation is meant to be included into Scikit-Learn pipelines.

Pipeline steps "communicate" with each other using 2-D data matrices. They do not communicate using scalar values.

If you're trying to use `ExpressionTransformer` outside of a pipeline, then you still need to present data to its `transform(X)` method as a row vector.

**Comment by vruusmann** [comment]
Also, if you want to convert arbitrary Python expressions or functions to PMML, then you better use the [JPMML-Python](https://github.com/jpmml/jpmml-python) libraries and command-line applications directly.

The idea is to choose a different `org.jpmml.python.Scope` implementation class.

The `EstimatorTransformer` is hard-coded to use the `org.jpmml.python.DataFrameScope` subclass, which stipulates that the only visible variable is `X`, whose type is row vector.

There's an alternative `org.jpmml.python.BlockScope` subclass, which lets you have any number/any name/any type variables.

**Comment by liuhuanshuo** [comment]
> Also, if you want to convert arbitrary Python expressions or functions to PMML, then you better use the [JPMML-Python](https://github.com/jpmml/jpmml-python) libraries and command-line applications directly.

Thanks, if I have time, I will learn this library

However, for the current problem, I haven't found a good way to handle it in Python, so here is a simple code demonstration.

As you can see, this code executes, but it can't be saved. How do I fix it?
```
df = pd.DataFrame({"col_1": [1, 2, 3]})

mapper_encode_ = [
    
 ('col_1',ExpressionTransformer("100 if X > 1 else 0")),
]

mapper = DataFrameMapper(mapper_encode_, input_df=True,df_out=True)
pp = PMMLPipeline(
    steps=[
        ("mapper", mapper)])

pp.fit_transform(df)

>>>
      col_1 
0	0
1	100
2	100
```

**Comment by vruusmann** [comment]
Pay attention to your `DataFrameMapper` column selection syntax!

Right now, you do:
```python
mapper_encode_ = [
  ('col_1', ExpressionTransformer("100 if X > 1 else 0")),
]
```

You should be doing:
```python
mapper_encode_ = [
  (['col_1'], ExpressionTransformer("100 if X > 1 else 0")),
]
```

I'm wrapping the column name between square brackets `[` and `]`, (ie. `["col_1"]` instead of `"col_1"`), which causes the `DataFrameMapper` to convert this column from (pseudo-)scalar to array type.

I haven't tested, but I assume that with the updated column selection syntax, the `X[0]` construct will work OK.
