### ISSUE TITLE
`SEVERE: Failed to convert` in pmml output

### ISSUE THREAD

**Issue by sam-s** [jpmml/sklearn2pmml#55]
All of sudden (worked a month ago!) PMML output for a `GradientBoostingClassifier` is broken:
```
Aug 24, 2017 10:42:14 AM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Aug 24, 2017 10:42:14 AM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 78 ms.
Aug 24, 2017 10:42:14 AM org.jpmml.sklearn.Main run
INFO: Converting..
Aug 24, 2017 10:42:14 AM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.NullPointerException
	at org.jpmml.converter.ValueUtil.asInt(ValueUtil.java:103)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.getNumberOfFeatures(GradientBoostingClassifier.java:49)
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:129)
	at org.jpmml.sklearn.Main.run(Main.java:144)
	at org.jpmml.sklearn.Main.main(Main.java:93)

Exception in thread "main" java.lang.NullPointerException
	at org.jpmml.converter.ValueUtil.asInt(ValueUtil.java:103)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.getNumberOfFeatures(GradientBoostingClassifier.java:49)
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:129)
	at org.jpmml.sklearn.Main.run(Main.java:144)
	at org.jpmml.sklearn.Main.main(Main.java:93)
```
to reproduce:
```
import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier
from sklearn2pmml import sklearn2pmml, PMMLPipeline
df=pd.DataFrame({"ta":[0,0,0,1,1,1],"a":[0,1,2,3,4,5],"b":[5,4,3,2,1,0]})
active_fields=["a","b"]
clf=GradientBoostingClassifier().fit(df.loc[:,active_fields],df.ta)
pipe=PMMLPipeline([("classifier", clf)])
pipe.target_field="ta"
pipe.active_fields=np.array(active_fields)
sklearn2pmml(pipe, "tmp.pmml", with_repr=True)
```
Note that I do _not_ want to use `sklearn2pmml` to train models, only to save them as pmml.

**Comment by vruusmann** [comment]
Let me guess (as you're not showing me your Python package versions) - you upgraded from Scikit-Learn 0.18.X to 0.19.0 not long time ago?

This is a known issue - the data structure of `GradientBoostingClassifier` class has changed in Scikit-Learn 0.19.0. This issue is manifested if the PMML pipeline does not contain explicit feature information (eg. the first step of PMML pipeline is not a `DataFrameMapper`), and the JPMML-SkLearn library attempts to query the estimator about it.

**Comment by vruusmann** [comment]
> The data structure of GradientBoostingClassifier class has changed in Scikit-Learn 0.19.0.

Specifically, the `GradientBoostingClassifier.n_features` attribute has been converted from a "static attribute" to a "dynamic attribute", which Java cannot see.

**Comment by sam-s** [comment]
Indeed, `sklearn.__version__` is `0.19.0`.
It seems that you can find `n_features` as `len(pipe.active_fields)`.

How do I fix this issue in the meantime?
Is there a way to create a "trivial" `DataFrameMapper` that would specify `n_features` and little else?

Thanks!

**Comment by sam-s** [comment]
I tried
```
from sklearn_pandas import DataFrameMapper
pipe=PMMLPipeline([
  ("mapper",DataFrameMapper([(["ta","a","b"],None)])),
  ("classifier", clf)
])
```
and got the same error.

**Comment by vruusmann** [comment]
> and got the same error.

The JPMML-SkLearn library knows that `GradientBoostingClassifier` has the `n_features` attribute, and attempts to fetch it anyway - the goals is to perform an extra sanity check: `n_features(DataFrameMapper) == n_features(GradientBoostingClassifier)`

**Comment by sam-s** [comment]
I see - so the bug is in `JPMML-SkLearn` rather than `sklearn2pmml`, right?
What is the next step?
Do I need to report it there?
Will you move this issue there?
Any chance this issue will be fixed? Soon?
Thank you very much!

**Comment by vruusmann** [comment]
> so the bug is in JPMML-SkLearn rather than sklearn2pmml, right?

`sklearn2pmml` is a thin Python wrapper around `JPMML-SkLearn`. If the conversion fails with a Java exception (eg. `java.lang.NullPointerException`, `java.lang.IllegalArgumentException` etc), then it's the JPMML-SkLearn layer that is misbehaving.

> Do I need to report it there?

Here is just as good as there.

> Will you move this issue there?

AFAIK, it's not possible to move issues from one GitHub project to another.

However, it is possible to cross-reference projects in commit messages, so when the bug gets fixed in the JPMML-SkLearn library, then this issue will be closed automatically, and notifications will be delivered to all interested parties.

> Any chance this issue will be fixed? Soon?

I've got other priorities at the moment - waiting for some paying customer to complain first.
