### ISSUE TITLE
The value of the sklearn.linear_model.logistic.LogisticRegression.classes_ attribute (null) is not a supported array type

### ISSUE THREAD

**Issue by akari0725** [jpmml/sklearn2pmml#64]
Please forgive my terrible English~

This is a demo program, for test how to export an pmml pipeline from sklearn, and then I want to use it in spark.

now I'm trying to export a pmml file from sklearn, 

I use Anaconda with python3.6, scikit-learn 0.18.1, sklearn2pmml 0.26.0, sklearn-pandas 1.6.0

there is my code, first, I built a new DataSet:

```
from sklearn import datasets
import matplotlib.pyplot as plt
X, y = datasets.make_classification(n_samples=500, n_features=2, n_redundant=0, n_clusters_per_class=1, n_classes=2)
plt.scatter(X[:, 0], X[:, 1], marker='o', c=y)
plt.show()

matrix = np.column_stack((X, np.mat(y).T))
from pandas import DataFrame
df = DataFrame(matrix, columns=['x0','x1','y'])
df.to_csv('./dataset.csv', index=False, encoding='utf-8', sep=',')
```

and then:

```
import pandas as pd
df = pd.read_csv('./dataset.csv', header = 0, error_bad_lines = False, encoding = 'utf-8', sep = ',')
df.head()

from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1, test_size=0.3, random_state=0)
for train_index, test_index in split.split(df, df['y']):
    train_set_df = df.loc[train_index]
    test_set_df = df.loc[test_index]

X_train = train_set_df.ix[:,['x0', 'x1']]
X_test = test_set_df.ix[:,['x0', 'x1']]
y_train = train_set_df.ix[:,['y']]
y_test = test_set_df.ix[:,['y']]

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

from sklearn.preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures(degree=2, include_bias=False)
poly_features.fit(X_train)
```

at last I'm trying to export this pipeline:

```
from sklearn2pmml import PMMLPipeline

step1 = ('scaler', scaler)
step2 = ('poly_features', poly_features)
step3 = ('classifier', LogisticRegression(penalty='l2', C=0.01))
pipeline_pmml = PMMLPipeline([setp0, step1, step2, step3])

from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline_pmml, './lr.pmml')
```

but I got a Java Error:

```
The JPMML-SkLearn conversion application has failed. The Java process should have printed more information about the failure into its standard output and/or error streams

Exception in thread "main" java.lang.IllegalArgumentException: The value of the sklearn.linear_model.logistic.LogisticRegression.classes_ attribute (null) is not a supported array type
	at org.jpmml.sklearn.ClassDictUtil.getArray(ClassDictUtil.java:52)
	at sklearn.Classifier.getClasses(Classifier.java:49)
	at sklearn.EstimatorUtil.getClasses(EstimatorUtil.java:37)
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:100)
	at org.jpmml.sklearn.Main.run(Main.java:144)
	at org.jpmml.sklearn.Main.main(Main.java:93)
```

Please help me, thx!

**Comment by vruusmann** [comment]
> step3 = ('classifier', LogisticRegression(penalty='l2', C=0.01))

The `LogisticRegression` object instance is currently uninitialized - you haven't invoked its `fit(X, y)` method, which takes care of initializing the `LogisticRegression.classes_` attribute.

So, if you do `LogisticRegression.fit(X, y)` before constructing the `PMMLPipeline` object, then this exception should be resolved.

> pipeline_pmml = PMMLPipeline([setp0, step1, step2, step3])

This is correct application code, but it's going to be rather difficult to maintain long-term. I would suggest you to check out the `sklearn2pmml.make_pmml_pipeline` function, which lets you convert "regular" fitted Scikit-Learn pipeline objects to `PMMLPipeline` objects like this:
```Python
pipeline = train_normal_pipeline()

from sklearn2pmml import make_pmml_pipeline
pipeline = make_pmml_pipeline(pipeline, active_fields = [...], target_fields = [...])

from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline, "pipeline.pmml")
```

I've just published the following presentation about SkLearn2PMML/JPMML-SkLearn capabilities: https://www.slideshare.net/VilluRuusmann/converting-scikitlearn-to-pmml

> split = StratifiedShuffleSplit(n_splits=1, test_size=0.3, random_state=0)

The `StratifiedShuffleSplit` transformer type is currently not supported by SkLearn2PMML, so if you start using the `make_pmml_pipeline` approach, then the conversion is likely to fail again.

However, it will be trivial to support it in the future, because the `StratifiedShuffleSplit` transformation (and many other transformations in the `sklearn.model_selection` module) are no-op from the PMML perspective.

As a temporary workaround, you could tweak my `make_pmml_pipeline` function, and simply filter out the `StratifiedShuffleSplit` step(s).

**Comment by akari0725** [comment]
Thank you for your answer, it works successfully by your suggest!
