### ISSUE TITLE
Java 9 incompatibility 

### ISSUE THREAD

**Issue by urigoren** [jpmml/sklearn2pmml#80]
When running the module with Java9, this error occur

> Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)

After downgrading to JAVA8, all works well

**Comment by vruusmann** [comment]
The default configuration of Java9 runtime does not include Java XML Binding (JAXB) libraries. They need to be "activated" using some Java/JVM command-line options.

Probably, the solution is available via #28.

**Comment by urigoren** [comment]
Hi Villu,
Thank you for the super swift response.

I've read in:
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

That this issue could be solved by adding `-add-modules java.se.ee` to the java command-line.

I think the python package should check the java version installed, and append this command-line configuration if needed.

**Comment by vruusmann** [comment]
> I think the python package should check the java version installed

The ability to query Java version was introduced not so long time ago:
https://github.com/jpmml/sklearn2pmml/blob/master/sklearn2pmml/__init__.py#L196-L209

You can try tweaking the SkLearn2PMML package locally and see if it works.

> That this issue could be solved by adding -add-modules java.se.ee to the java command-line.

Haven't got Java9 installed in my computer (actually, the JPMML family of libraries is still targeting Java7), so I've been blissfully ignorant about this Java versioning issue.

The SkLearn2PMML package depends on the JPMML-SkLearn library, which in turn depends on JPMML-Converter and JPMML-Model libraries. As a long-term solution, I should investigate Java9 module mechanism, and try to customize JPMML-Model build process so that the JAXB module would be part of the package (probably, the distributable JAR file needs to contain some (meta-)descriptor file with module dependency information).

**Comment by damienrj** [comment]
I ran into this issue as well. As least on OSX you can switch between java versions pretty easily. 

`export JAVA_HOME=`/usr/libexec/java_home -v 1.8` for example.

**Comment by damienrj** [comment]
Adding `--add-modules java.se.e` to the command works fine for Java 9.  Given that the pull request was closed I take it there will be no java 9 support coming?
https://github.com/jpmml/sklearn2pmml/pull/92
