### ISSUE TITLE
Meta-transformer for customizing field names

### ISSUE THREAD

**Issue by AndreDCMartins** [jpmml/sklearn2pmml#82]
We want to be able to apply different Lookup transformations to the same categorical feature.
In our case, we want to apply a mapping that uses an average and another that uses the standard deviation and generate two different DerivedFields.

When we do it, the conversion to PMML fails because it tries to create two derived fields with the same name: "lookup(<feature_name>)". The error message is:

```
java.lang.IllegalArgumentException: lookup(<feature_name>)
	at org.jpmml.converter.PMMLEncoder.checkName(PMMLEncoder.java:233)
	at org.jpmml.converter.PMMLEncoder.addDerivedField(PMMLEncoder.java:127)
	at org.jpmml.converter.PMMLEncoder.createDerivedField(PMMLEncoder.java:137)
	at sklearn2pmml.preprocessing.LookupTransformer.encodeFeatures(LookupTransformer.java:134)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
	at sklearn.Initializer.encodeFeatures(Initializer.java:53)
```

I would expect `PMMLEncoder.addDerivedField` to generate a new Derived Field Name (e.g. append "_v2") when it finds an existing field with the same name.

Is there any way to change this behaviour?
Or is there a workaround? For instance apply a Dummy Transformer to rename the initial field before applying the second LookupTransformer?

Related to issue: https://github.com/jpmml/sklearn2pmml/issues/70

**Comment by vruusmann** [comment]
> Or is there a workaround?

Probably could set up some branched workflow using the `FeatureUnion` meta-transformer, where the original categorical features is renamed in the beginning of both branches, so that you'd end up having `lookup(identitytransform(cat_feature))` and `lookup(cat_feature)`.

You can code up such "feature rename" transformation quite easily. The PMML representation of such transformation:
```XML
<PMML>
  <DataDictionary>
    <DataField name="x" dataType="string" optype="categorical"/>
  </DataDictionary>
  <TransformationDictionary>
    <!-- Same dataType and optype attribute values, but a different name attribute value-->
    <DerivedField name="alias(x)" dataType="string" optype="categorical">
      <FieldRef field="x"/>
    </DerivedField>
  </TransformationDictionary>
</PMML>
```

**Comment by vruusmann** [comment]
There's another idea of transformer "aliases", which I quite haven't figured out and implemented yet.

In brief, it should be possible to assign a "alias" attribute to fitted transformer instances. If this attribute is set, then the JPMML-SkLearn library would generate the field name based on this hint, otherwise it would fall back to the default name.

**Comment by AndreDCMartins** [comment]
Can you please explain the idea of the workaround using the `identitytransform`? Which transformers would I use?
I have searched and I couldn't find any identity transformer in the repo.

**Comment by vruusmann** [comment]
Technically, `FunctionTransformer(None)` performs an identity transform, but it won't let you customize the name of the resulting feature (so, if you send `x` in, then `x` will come out as well).

You'll be much better off by implementing a custom "feature rename" transformation.

**Comment by vruusmann** [comment]
> Building it in sklearn2pmml-plugin has the extra complexity of then deploying the egg and jar files to our deployment environments.

If you fork SkLearn2PMML and JPMML-SkLearn projects, then you would end up maintaining, packaging and deploying **_many more_** egg and jar files.
