### ISSUE TITLE
How to add id attribute with Node?

### ISSUE THREAD

**Issue by chrislee87** [jpmml/sklearn2pmml#95]
Using sklearn2pmml I have a pmml file with nodes only have the score attribute,
`<Node score="1.4269325048455135">`

The code to generate pmml file as below
```Python
pipeline = PMMLPipeline([
	("classifier", GradientBoostingClassifier())
])
pipeline.fit(X_train, y_train)
sklearn2pmml(pipeline, "GBClassifier.pmml", with_repr = True)
```

I need the nodes have both id and score, what should I do?
`<Node id="3" score="0.0016095485514608788">`

**Comment by vruusmann** [comment]
> I need the nodes have both id and score, what should I do?

You need to disable re-encoding decision trees, which is active by default. The re-encoding makes decision tree PMML files 50% smaller, but since the structure of the decision tree changes substantially, then node identifiers must be removed.

You can enable/disable decision tree conversion options using the `sklearn2pmml.pipeline.PMMLPipeline.configure(**pmml_options)` method:
https://github.com/jpmml/sklearn2pmml/blob/master/sklearn2pmml/pipeline/__init__.py#L58-L62

In the current case, do the following:
```Python
pipeline = PMMLPipeline([...])
pipeline.fit(X_train, y_train)
pipeline.configure(compact = False, flat = False, winner_id = True)
sklearn2pmml(pipeline, ...)
```

The last option (`winner_id = True`) also causes a special-purpose `OutputField` element to be generated.
